name: GPT Commit Summary
# Summary: This action will write a comment about every commit in a pull request, containing major points

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - uses: dirtycajunrice/gpt-commit-summarizer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
